### PR TITLE
docs: mention admin decorators in Django 3.2+.

### PR DESCRIPTION
**Pull request by ngnpope**
See https://docs.djangoproject.com/en/stable/releases/3.2/#new-decorators-for-the-admin-site

~~I'm creating this as a draft until Django 3.2 is released.~~

- [x] Prior to merging we should update the links to use `.../stable/...` instead of `.../3.2/...`.

### CODE REVIEW

**Comment by escaped** [comment]
Wow... That's amazing that this somehow made its way into Django core :) Thanks a lot for persuing on this and doing all the hard work. :heart: 

I guess it would be great to reference this project in Django as well, so people are able to use this feature in earlier versions. @pope1ni  Do you think that feasible?
Additionally, it would make sense to slightly update this repo as well, so the function signature is compatible with the official version (https://github.com/escaped/django-admin-display/issues/12).

**Comment by ngnpope** [comment]
> Wow... That's amazing that this somehow made its way into Django core :) Thanks a lot for persuing on this and doing all the hard work. ❤️ 

Thanks! I think it'll be handy for people new to Django and make these options more discoverable.

> I guess it would be great to reference this project in Django as well, so people are able to use this feature in earlier versions. @pope1ni Do you think that feasible?

I'm not sure what would be feasible or not here. Perhaps you could speak to one of the Django fellows about this.

> Additionally, it would make sense to slightly update this repo as well, so the function signature is compatible with the official version (#12).

Yes, I did notice that the signature was different here using the function attribute names. I made a decision when implementing the decorators to remove some of the verbosity as we had an opportunity to clean up the API and make it more friendly. See https://github.com/django/django/pull/13532.

**Comment by ngnpope** [comment]
@escaped Django 3.2 is released! I've updated this and marked it ready for review.

**Review by escaped — APPROVED** [review]
Nice. Thank you!

**Pull request merged**
